### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by dzwiedziu-nkg** [imrabti/gwtp-spring-security#3]
I look it. Sounds nice. But I want to run it and try to use but I don't know how :(
I think is a lot of people who want to try your example but they don't know how. I must analyse your source code to find out how to use.

Please write:
1/ How to compile (I know, mvn package)
2/ How to run (download Tomcat, deploy war and run Tomcat however I suggest use plugin from maven that can run via single mvn command like mvn tomcat7:run)
3/ URL to open in browser
4/ Default login and password (root/password)
5/ Test Scenario for users

Nowadays people are lazy. When they can't run and try quickly then they leave and looking for others.

**Comment by imrabti** [comment]
Noted I'll try to offer a documentation as soon as possible.
There is also an article I wrote about this : https://crazygui.wordpress.com/2014/08/29/secure-rest-services-using-spring-security/

**Comment by imrabti** [comment]
I'm in the processing of updating this code in a separate branch, did successfully migrate it to Spring boot 1.3.
Now it should be easy to run, just by executing the jar, later I'll add a small Read-Me to describe how.
